sudo: required
language: generic
#add dependencies
services:
 - docker
##build test version of React project
before_install:
  - docker build -t madalynharger/react-test -f ./client/Dockerfile.dev ./client
#Run tests
script:
  - docker run -e CI=true madalynharger/react-test npm test
#Build prod versions of all projects
after_success:
  - docker build -t madalynharger/multi-client ./client
  - docker build -t madalynharger/multi-nginx ./nginx
  - docker build -t madalynharger/multi-server ./server
  - docker build -t madalynharger/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push madalynharger/multi-client
  - docker push madalynharger/multi-nginx
  - docker push madalynharger/multi-server
  - docker push madalynharger/multi-worker

  #have elastic beanstalk deploy them
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-668238319068'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY